### PR TITLE
Fixed an issue where muted users could execute commands.

### LINKED ISSUE #73: Bug: muted users can still execute commands, though their command message is deleted
Reproduction steps:

1. Mute yourself / another user
2. Execute any command / let a muted user execute any command
3. ChatBot responds to the command and executes the command
4. ChatBot sees that you / another user is muted and deletes your message

The reply of ChatBot is still in the channel. This means that you can indirectly spam a channel by spamming commands, even though you are muted.

### PR DESCRIPTION
**Pull request by McJeffr**
See #73.

### CODE REVIEW

File: src/Command.js [hunk 1]
```diff
@@ -17,6 +18,10 @@ module.exports = BotModule.extend({
         this._super(dependencyGraph);
 
         this.discordClient.on('message', message => {
+            if (RoleHelper.isMuted(message.member)) {
+                return;
```
Comment (McJeffr) [inline src/Command.js:22]: The Utility/Muted.js will delete the message for us.

File: src/Helper/RoleHelper.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
+const config = require('config');
+
+module.exports = {
+    hasRoles: function (member) {
```
Comment (navarr) [inline src/Helper/RoleHelper.js]:
```suggestion
    hasRole: function (member, role) {
        return this.hasRoles(member) && member.roles.cache.has(role);
    },
    hasRoles: function (member) {
```

File: src/Helper/RoleHelper.js [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+        return member !== null && member.roles.cache.array().length > 0;
+    },
+    isMuted: function (member) {
+        return this.hasRoles(member) && member.roles.cache.has(config.mutedRole);
```
Comment (navarr) [inline src/Helper/RoleHelper.js]:
```suggestion
        return this.hasRole(member, config.mutedRole);
```

File: src/Helper/RoleHelper.js [hunk 4]
```diff
@@ -0,0 +1,21 @@
+const config = require('config');
```
Comment (navarr) [inline src/Helper/RoleHelper.js]: I would suggest renaming this file to `RoleDeterminer` to clarify and limit its purpose.

**Review by navarr — CHANGES_REQUESTED** [review]

File: src/Helper/RoleHelper.js (hunk 2 above)
Comment (McJeffr) [reply src/Helper/RoleHelper.js]: hasRole is already a part of the Discord.js implementation, there would be little use to implement it like this. This function in particular checks if a user has any role assigned to it.

Comment (McJeffr) [reply src/Helper/RoleHelper.js]: Additionally, the reason for the muted / administrator functions is because those are from config. In the case of administrator, it's a collection of possible administrator roles.

File: src/Helper/RoleHelper.js (hunk 3 above)
Comment (McJeffr) [reply src/Helper/RoleHelper.js]: I think that with v12, this ported functionality from v11 might be rather pointless actually. I'll see if it can simply be dropped without issues.

**Comment by McJeffr** [comment]
Restructured the RoleHelper (now RoleDeterminer) to be a bit more useful. The `hasRoles`-function is no longer really needed with v12's RoleManager objects. Additionally, added `hasRole`, which takes in a member and a role _name_. The discord.js implementation only supports quick access through RoleResolvables (ids / role objects), not role names.

**Review by navarr — APPROVED** [review]
